# base image https://hub.docker.com/_/python
# FROM python:3-alpine
FROM psazuse.jfrog.io/krishnam-docker-virtual/python:3-alpine

RUN apk add build-base

WORKDIR /app
COPY app/. /app/
WORKDIR /app

RUN pip3 install gunicorn
RUN pip3 install -r test-requirements.txt
RUN python3 -m compileall .
RUN FLASK_APP=app.py
CMD [ "flask", "run", "--host", "0.0.0.0"]